# Generated by Django 4.2.2 on 2023-06-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotto', '0001_initial'),
        ('ordine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento_Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_del_prodotto', models.IntegerField()),
                ('prezzo_del_prodotto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordine.ordine')),
                ('id_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotto.prodotto')),
            ],
            options={
                'verbose_name_plural': 'Elemento_ordine',
            },
        ),
    ]
