# Generated by Django 4.2 on 2023-06-08 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ordine", "0003_alter_ordine_data_ordine"),
        ("elemento_ordine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elemento_ordine",
            name="id_ordine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elementi_ordine",
                to="ordine.ordine",
            ),
        ),
    ]
