# Generated by Django 4.2.2 on 2023-06-07 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotto', '0001_initial'),
        ('carrello', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrello',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi_carrello', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrello',
            name='id_prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='prodotto.prodotto'),
        ),
    ]
