# Generated by Django 4.2 on 2023-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodotto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="immagine_categoria",
            field=models.ImageField(
                default="logobg.png", upload_to="immagini_categoria/"
            ),
        ),
    ]
