# Generated by Django 4.2.2 on 2023-06-07 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totale_pagamento', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_pagamento', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordine.ordine')),
            ],
            options={
                'verbose_name_plural': 'Pagamenti',
            },
        ),
    ]
