# Generated by Django 4.2 on 2023-06-10 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamento", "0002_remove_pagamento_totale_pagamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 10, 12, 10, 35, 694663)
            ),
        ),
    ]
