# Generated by Django 4.1 on 2023-06-09 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordine', '0006_alter_ordine_data_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ordine',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 15, 20, 38, 52551)),
        ),
    ]
