# Generated by Django 4.2 on 2023-06-10 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordine", "0007_alter_ordine_data_ordine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordine",
            name="data_ordine",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 10, 12, 10, 35, 693699)
            ),
        ),
        migrations.AlterField(
            model_name="ordine",
            name="stato_ordine",
            field=models.TextField(
                choices=[("inserito", "inserito"), ("pagato", "pagato")],
                default="inserito",
            ),
        ),
    ]
