# Generated by Django 4.1 on 2023-06-10 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordine', '0008_alter_ordine_data_ordine_alter_ordine_stato_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ordine',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 14, 12, 57, 843429)),
        ),
    ]
